name: Quality assure - Lint, Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Prepare Repository
        uses: actions/checkout@v2

      - name: 🧩 Install Dependencies
        run: npm ci

      - name: 🧹 Run Linting
        run: npm run lint

      - name: 🧪 Run Test
        run: npm run test